site_name: pygravmag3d
repo_url: https://github.com/ruboerner/pygravmag3d  # or your repo
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - API: reference.md

docs_dir: docs_src
site_dir: docs